<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Migration_Add_instansi extends CI_Migration {

	public function up() {
		$this->dbforge->add_field(array(
                        'id' => array(
                                'type' => 'integer',
                                'auto_increment' => TRUE
                        ),
                        'nama_instansi' => array(
                               'type'   => 'VARCHAR',
                                'constraint' => '255',
                                'null' => TRUE,
                        ),
                        'nama_singkat' => array(
                               'type'   => 'VARCHAR',
                                'constraint' => '255',
                                'null' => TRUE,
                        ),
                        'parent' => array(
                               'type'   => 'integer',
                                'null' => TRUE,
                        ),
                        'type' => array(
                                'type'   => 'VARCHAR',
                                'constraint' => '20',
                                'null' => TRUE,
                        ),
                        'position_order' => array(
                                'type'   => 'integer',
                                'null' => TRUE,
                        ),
                       'kategori_instansi' => array(
                               'type'   => 'VARCHAR',
                                'constraint' => '20',
                                'null' => TRUE,
                        ),
                        'join_dept' => array(
                               'type'   => 'integer',
                                'null' => TRUE,
                        ),
                        'status' => array(
                               'type'   => 'integer',
                                'null' => TRUE,
                                'default' => 1
                        ),
               ));
                $this->dbforge->add_key('id', TRUE);
                $this->dbforge->create_table('_instansi');

					$data = array(
					   array('nama_instansi' 	=> 'Kabupen Agam', 
					   		 'parent' 		 	=> 0,
					   		 'type' 		 	=> 'non_instansi', 
					   		 'position_order' 	=> 1,
					   		 'kategori_instansi'=> Null,
					   		 'join_dept' 		=> Null
					   		),
					   array('nama_instansi' 	=> 'Sekretaris Daerah', 
					   		 'parent' 		 	=> 1,
					   		 'type' 		 	=> 'opd', 
					   		 'position_order'	=> 1,
					   		 'kategori_instansi'=> 'sekda',
					   		 'join_dept' 		=> 2
					   		),
					   array('nama_instansi' 	=> 'Bagian Pengadaan Barang/Jasa', 
					   		 'parent' 		 	=> 2,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 1,
					   		 'kategori_instansi' => 'bagian',
					   		 'join_dept' 		=> 2
					   		),
					   array('nama_instansi' 	=> 'Bagian Pemerintahan dan Otonomi Daerah', 
					   		 'parent' 		 	=> 2,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 2,
					   		 'kategori_instansi' => 'bagian',
					   		 'join_dept' 		=> 2
					   		),
					   array('nama_instansi' 	=> 'Bagian Kesejahteraan Rakyat', 
					   		 'parent' 		 	=> 2,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 3,
					   		 'kategori_instansi' => 'bagian',
					   		 'join_dept' 		=> 2
					   		),
					   array('nama_instansi' 	=> 'Bagian Administrasi Pembangunan', 
					   		 'parent' 		 	=> 2,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 4,
					   		 'kategori_instansi' => 'bagian',
					   		 'join_dept' 		=> 2
					   		),
					   array('nama_instansi' 	=> 'Bagian Perekonomian dan Sumber Daya Alam', 
					   		 'parent' 		 	=> 2,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 5,
					   		 'kategori_instansi' => 'bagian',
					   		 'join_dept' 		=> 2
					   		),
					   array('nama_instansi' 	=> 'Bagian Bagian Hukum', 
					   		 'parent' 		 	=> 2,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 6,
					   		 'kategori_instansi' => 'bagian',
					   		 'join_dept' 		=> 2
					   		),
					   array('nama_instansi' 	=> 'Bagian Perencanaan dan Keuangan Sekretariat Daerah', 
					   		 'parent' 		 	=> 2,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 7,
					   		 'kategori_instansi' => 'bagian',
					   		 'join_dept' 		=> 2
					   		),
					   array('nama_instansi' 	=> 'Bagian Infrastruktur', 
					   		 'parent' 		 	=> 2,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 8,
					   		 'kategori_instansi' => 'bagian',
					   		 'join_dept' 		=> 2
					   		),
					   array('nama_instansi' 	=> 'Bagian Organisasi dan Reformasi Birokrasi', 
					   		 'parent' 		 	=> 2,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 9,
					   		 'kategori_instansi' => 'bagian',
					   		 'join_dept' 		=> 2
					   		),
					   array('nama_instansi' 	=> 'Bagian Protokol dan Komunikasi Pimpinan Sekretariat Daerah', 
					   		 'parent' 		 	=> 2,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 10,
					   		 'kategori_instansi' => 'bagian',
					   		 'join_dept' 		=> 2
					   		),
					    array('nama_instansi' 	=> 'Bagian Umum', 
					   		 'parent' 		 	=> 2,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 11,
					   		 'kategori_instansi' => 'bagian',
					   		 'join_dept' 		=> 2
					   		),
					    array('nama_instansi' 	=> 'Sekretariat DPRD', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 2,
					   		 'kategori_instansi' => 'setwan',
					   		 'join_dept' 		=> 3
					   		),
					    array('nama_instansi' 	=> 'inspektorat', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 3,
					   		 'kategori_instansi' => 'inspektorat',
					   		 'join_dept' 		=> 4
					   		),
					     array('nama_instansi' 	=> 'Badan Kepegawaian dan Pengembangan Sumber Data Manusia', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 4,
					   		 'kategori_instansi' => 'badan',
					   		 'join_dept' 		=> 5
					   		),
					      array('nama_instansi' 	=> 'Badan Kesatuan Bangsa dan Politik', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 5,
					   		 'kategori_instansi' => 'badan',
					   		 'join_dept' 		=> 6
					   		),
					      array('nama_instansi' 	=> 'Badan Keuangan Daerah', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 6,
					   		 'kategori_instansi' => 'badan',
					   		 'join_dept' 		=> 7
					   		),
					      array('nama_instansi' 	=> 'Badan Penanggulangan Bencana Daerah', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 7,
					   		 'kategori_instansi' => 'badan',
					   		 'join_dept' 		=> 8
					   		),
					      array('nama_instansi' 	=> 'Badan Perencanaan Pembangunan Daerah', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 8,
					   		 'kategori_instansi' => 'badan',
					   		 'join_dept' 		=> 9
					   		),
					      array('nama_instansi' 	=> 'Dinas Arsip dan Perpustakaan', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 9,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 10
					   		),
					      array('nama_instansi' 	=> 'Dinas Kependudukan dan Pencatatan Sipil', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 10,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 11
					   		),
					       array('nama_instansi' 	=> 'Dinas Kesehatan', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 11,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 1800
					   		),
					       array('nama_instansi' 	=> 'Dinas Komunikasi dan Informatika', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 12,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 36
					   		),
					       array('nama_instansi' 	=> 'Dinas Lingkungan Hidup', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 13,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 37
					   		),
					       array('nama_instansi' 	=> 'Dinas Pariwisata dan Olahraga', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 14,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 38
					   		),
					       array('nama_instansi' 	=> 'Dinas Pekerjaan Umum dan Tata Ruang', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 15,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 39
					   		),
					       array('nama_instansi' 	=> 'Dinas Pemberdayaan Masyarakat dan Nagari', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 16,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 40
					   		),
					       array('nama_instansi' 	=> 'Dinas Penanaman Modal Pelayanan Terpadu Satu Pintu dan Ketenagakerjaan', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 17,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 41
					   		),
					       array('nama_instansi' 	=> 'Dinas Pengendalian Penduduk Keluarga Berencana Pemberdayaan Perempuan dan Perlindungan Anak', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 18,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 42
					   		),
					       array('nama_instansi' 	=> 'Dinas Pendidikan dan Kebudayaan', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 19,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 1798
					   		),
					        array('nama_instansi' 	=> 'Dinas Pehubungan', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 20,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 101
					   		),
					   		 array('nama_instansi' 	=> 'Dinas Perikanan dan Ketahanan Pangan', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 21,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 102
					   		),
					   		  array('nama_instansi' 	=> 'Dinas Perindustrian Perdaganan Koperasi Usaha Kecil dan Menengah', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 22,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 103
					   		),
					   		 array('nama_instansi' 	=> 'Dinas Pertanian', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 23,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 104
					   		),
					   		array('nama_instansi' 	=> 'Dinas Perumahan Rakyat dan Kawasan Pemukiman', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 24,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 105
					   		),
					   		array('nama_instansi' 	=> 'Dinas Sosial', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 25,
					   		 'kategori_instansi' => 'dinas',
					   		 'join_dept' 		=> 106
					   		),
					   		array('nama_instansi' 	=> 'Satuan Polisi Pamong Praja dan Pemadam Kebakaran', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 26,
					   		 'kategori_instansi' => 'satpolpp',
					   		 'join_dept' 		=> 107
					   		),
					   		array('nama_instansi' 	=> 'RSUD Lubuk Basung', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 27,
					   		 'kategori_instansi' => 'rs',
					   		 'join_dept' 		=> 108
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Ampek Angkek', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 28,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 109
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Ampek Nagari', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 29,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 110
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Banuhampu', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 30,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 111
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Baso', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 31,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 112
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Canduang', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 32,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 113
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan IV Koto', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 33,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 114
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Kamang Magek', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 34,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 115
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Lubuk Basung', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 35,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 116
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Malalak', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 36,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 117
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Matur', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 37,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 118
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Palembayan', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 38,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 119
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Palupua', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 39,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 120
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Sungai Pua', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 40,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 121
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Tanjung Mutiara', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 41,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 122
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Tanjung Raya', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 42,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 123
					   		),
					   		array('nama_instansi' 	=> 'Kecamatan Tilatang Kamang', 
					   		 'parent' 		 	=> 1,
					   		 'type' 			=> 'opd', 
					   		 'position_order' 	=> 43,
					   		 'kategori_instansi' => 'camat',
					   		 'join_dept' 		=> 124
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Baso', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 1,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 13
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Batu Kambing', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 2,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 14
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Bawan Poskesri', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 3,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 15
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Biaro', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 4,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 16
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas IV Koto', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 5,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 17
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Kapau', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 6,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 18
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Koto Alam', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 7,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 19
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Lasi', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 8,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 20
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Lubuk Basung', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 9,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 21
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Magek', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 10,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 22
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Malalak Poskesri', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 11,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 23
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Manggopoh', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 12,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 24
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Maninjau', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 13,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 25
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Matur', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 14,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 26
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Muaro Putuih', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 15,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 27
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Padang Lua', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 16,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 28
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Padang Tarok', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 17,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 29
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Pakan Kamis', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 18,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 30
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Palembayan', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 19,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 31
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Palupuh', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 20,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 32
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Pasar Ahad', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 21,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 33
					   		),
					   		array('nama_instansi' 	=> 'Puskesmas Sungai Pua', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 22,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 34
					   		),
					   		array('nama_instansi' 	=> ' Puskesmas Tiku', 
					   		 'parent' 		 	=> 23,
					   		 'type' 			=> 'sub_opd', 
					   		 'position_order' 	=> 23,
					   		 'kategori_instansi' => 'puskesmas',
					   		 'join_dept' 		=> 35
					   		),
					 );
			         $this->db->insert_batch('_instansi', $data);
	
	}

	public function down() {
		$this->dbforge->drop_table('_instansi');
	}

}

/* End of file 026_add_instansi.php */
/* Location: ./application/migrations/026_add_instansi.php */